/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[34] = {10, 10, 0, 0, 0, 2, 7, 12, 16, 16, 19, 20, 21, 0, 1, 0, 1, 3, 4, 5, 0, 1, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5, 3, 6};
static const casadi_int casadi_s4[23] = {10, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s5[9] = {10, 3, 0, 1, 2, 3, 7, 8, 9};
static const casadi_int casadi_s6[3] = {10, 0, 0};

/* Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z:(i0[10],i1[10],i2[3],i3[],i4[],i5[3])->(o0[10x10,21nz],o1[10x10,10nz],o2[10x3,3nz],o3[10x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=sin(a1);
  a2=(a0*a2);
  a3=arg[0]? arg[0][4] : 0;
  a4=cos(a1);
  a4=(a3*a4);
  a2=(a2+a4);
  if (res[0]!=0) res[0][0]=a2;
  a2=cos(a1);
  a2=(a0*a2);
  a4=sin(a1);
  a4=(a3*a4);
  a2=(a2-a4);
  a2=(-a2);
  if (res[0]!=0) res[0][1]=a2;
  a2=cos(a1);
  a2=(-a2);
  if (res[0]!=0) res[0][2]=a2;
  a2=sin(a1);
  a2=(-a2);
  if (res[0]!=0) res[0][3]=a2;
  a2=2.8818443804034583e-01;
  a4=-1.0000000000000001e-01;
  a5=arg[0]? arg[0][7] : 0;
  a6=sin(a5);
  a7=1.8999999999999999e+00;
  a8=10.;
  a9=1.5875000000000000e-01;
  a10=arg[0]? arg[0][5] : 0;
  a11=(a9*a10);
  a11=(a11+a3);
  a12=9.9999999999999998e-13;
  a13=(a0+a12);
  a11=(a11/a13);
  a14=atan(a11);
  a14=(a8*a14);
  a15=(-a14);
  a15=atan(a15);
  a15=(a7*a15);
  a16=cos(a15);
  a17=(a11/a13);
  a18=1.;
  a11=casadi_sq(a11);
  a11=(a18+a11);
  a17=(a17/a11);
  a17=(a8*a17);
  a14=casadi_sq(a14);
  a14=(a18+a14);
  a17=(a17/a14);
  a17=(a7*a17);
  a17=(a16*a17);
  a19=(a6*a17);
  a4=(a4-a19);
  a4=(a2*a4);
  a4=(-a4);
  if (res[0]!=0) res[0][4]=a4;
  a4=1.7144999999999999e-01;
  a19=(a4*a10);
  a19=(a19-a3);
  a0=(a0+a12);
  a19=(a19/a0);
  a12=atan(a19);
  a12=(a12+a5);
  a12=(a8*a12);
  a20=atan(a12);
  a20=(a7*a20);
  a20=cos(a20);
  a21=(a19/a0);
  a19=casadi_sq(a19);
  a19=(a18+a19);
  a21=(a21/a19);
  a21=(a8*a21);
  a12=casadi_sq(a12);
  a12=(a18+a12);
  a21=(a21/a12);
  a21=(a7*a21);
  a21=(a20*a21);
  a22=cos(a5);
  a23=(a22*a17);
  a23=(a21+a23);
  a23=(a2*a23);
  if (res[0]!=0) res[0][5]=a23;
  a23=2.1222410865874362e+01;
  a24=cos(a5);
  a17=(a9*a17);
  a17=(a24*a17);
  a21=(a4*a21);
  a17=(a17+a21);
  a17=(a23*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][6]=a17;
  a17=sin(a1);
  if (res[0]!=0) res[0][7]=a17;
  a1=cos(a1);
  a1=(-a1);
  if (res[0]!=0) res[0][8]=a1;
  a1=(1./a11);
  a1=(a1/a13);
  a1=(a8*a1);
  a1=(a1/a14);
  a1=(a7*a1);
  a1=(a16*a1);
  a17=(a6*a1);
  a21=3.4700000000000002e+00;
  a25=(a21*a10);
  a17=(a17+a25);
  a17=(a2*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][9]=a17;
  a17=(a22*a1);
  a25=(1./a0);
  a25=(a25/a19);
  a25=(a8*a25);
  a25=(a25/a12);
  a25=(a7*a25);
  a25=(a20*a25);
  a17=(a17-a25);
  a10=(a21*a10);
  a17=(a17-a10);
  a17=(a2*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][10]=a17;
  a25=(a4*a25);
  a1=(a9*a1);
  a1=(a24*a1);
  a25=(a25-a1);
  a25=(a23*a25);
  a25=(-a25);
  if (res[0]!=0) res[0][11]=a25;
  a25=-1.;
  if (res[0]!=0) res[0][12]=a25;
  a13=(a9/a13);
  a13=(a13/a11);
  a13=(a8*a13);
  a13=(a13/a14);
  a13=(a7*a13);
  a16=(a16*a13);
  a6=(a6*a16);
  a13=(a21*a3);
  a6=(a6+a13);
  a6=(a2*a6);
  a6=(-a6);
  if (res[0]!=0) res[0][13]=a6;
  a0=(a4/a0);
  a0=(a0/a19);
  a0=(a8*a0);
  a0=(a0/a12);
  a0=(a7*a0);
  a0=(a20*a0);
  a22=(a22*a16);
  a22=(a0+a22);
  a21=(a21*a3);
  a22=(a22-a21);
  a22=(a2*a22);
  a22=(-a22);
  if (res[0]!=0) res[0][14]=a22;
  a16=(a9*a16);
  a24=(a24*a16);
  a0=(a4*a0);
  a24=(a24+a0);
  a24=(a23*a24);
  if (res[0]!=0) res[0][15]=a24;
  a15=sin(a15);
  a24=cos(a5);
  a24=(a15*a24);
  a24=(a2*a24);
  if (res[0]!=0) res[0][16]=a24;
  a8=(a8/a12);
  a7=(a7*a8);
  a20=(a20*a7);
  a7=sin(a5);
  a7=(a15*a7);
  a7=(a20+a7);
  a2=(a2*a7);
  a2=(-a2);
  if (res[0]!=0) res[0][17]=a2;
  a9=(a9*a15);
  a5=sin(a5);
  a9=(a9*a5);
  a4=(a4*a20);
  a9=(a9+a4);
  a23=(a23*a9);
  if (res[0]!=0) res[0][18]=a23;
  a23=-2.8818443804034585e-02;
  if (res[0]!=0) res[0][19]=a23;
  if (res[0]!=0) res[0][20]=a25;
  if (res[1]!=0) res[1][0]=a18;
  if (res[1]!=0) res[1][1]=a18;
  if (res[1]!=0) res[1][2]=a18;
  if (res[1]!=0) res[1][3]=a18;
  if (res[1]!=0) res[1][4]=a18;
  if (res[1]!=0) res[1][5]=a18;
  if (res[1]!=0) res[1][6]=a18;
  if (res[1]!=0) res[1][7]=a18;
  if (res[1]!=0) res[1][8]=a18;
  if (res[1]!=0) res[1][9]=a18;
  if (res[2]!=0) res[2][0]=a25;
  if (res[2]!=0) res[2][1]=a25;
  if (res[2]!=0) res[2][2]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Dynamic_Pacejka_model_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
